// consola.ts
export const consola = {
    mensagem: (...args: any[]) => console.log(...args),
    erro: (...args: any[]) => console.error(...args),
    advertencia: (...args: any[]) => console.warn(...args),
    info: (...args: any[]) => console.info(...args),
    depuracao: (...args: any[]) => console.debug(...args),
    rastreio: (...args: any[]) => console.trace(...args),
    tempo: (nome: string) => console.time(nome),
    tempoFim: (nome: string) => console.timeEnd(nome),
    grupo: (...args: any[]) => console.group(...args),
    grupoFim: () => console.groupEnd(),
    tabela: (dados: any) => console.table(dados),
    limpar: () => console.clear(),
    afirmar: (condicao: boolean, ...args: any[]) => console.assert(condicao, ...args),
    mostrar: (obj: any) => console.dir(obj),
    mostrarXML: (obj: any) => console.dirxml(obj),
    grupoColapsado: (...args: any[]) => console.groupCollapsed(...args),
    perfil: (rotulo: string) => console.profile(rotulo),
    terminarPerfil: () => console.profileEnd(),
    timeStamp: (rotulo: string) => console.timeStamp(rotulo),
    contador: (rotulo?: string) => console.count(rotulo),
    reiniciarContador: (rotulo?: string) => console.countReset(rotulo),
};
