// কনসোলা.ts
export const কনসোলা = {
    বার্তা: (...args: any[]) => console.log(...args),
    ত্রুটি: (...args: any[]) => console.error(...args),
    সতর্কতা: (...args: any[]) => console.warn(...args),
    তথ্য: (...args: any[]) => console.info(...args),
    ডিবাগ: (...args: any[]) => console.debug(...args),
    ট্রেস: (...args: any[]) => console.trace(...args),
    সময়: (নাম: string) => console.time(নাম),
    সময়শেষ: (নাম: string) => console.timeEnd(নাম),
    গোষ্ঠী: (...args: any[]) => console.group(...args),
    গোষ্ঠীশেষ: () => console.groupEnd(),
    টেবিল: (data: any) => console.table(data),
    পরিষ্কার: () => console.clear(),
    নিশ্চিতকরণ: (condition: boolean, ...args: any[]) => console.assert(condition, ...args),
    প্রদর্শন: (obj: any) => console.dir(obj),
    প্রদর্শনXML: (obj: any) => console.dirxml(obj),
    গোষ্ঠীসংক্ষেপ: (...args: any[]) => console.groupCollapsed(...args),
    প্রোফাইল: (label: string) => console.profile(label),
    প্রোফাইলশেষ: () => console.profileEnd(),
    সময়মুদ্রা: (label: string) => console.timeStamp(label),
    গণনা: (label?: string) => console.count(label),
    কাউন্টারপুনঃ_শুরু: (label?: string) => console.countReset(label),
};
