// consola.ts
export const consola = {
    mensaje: (...args: any[]) => console.log(...args),
    error: (...args: any[]) => console.error(...args),
    advertencia: (...args: any[]) => console.warn(...args),
    info: (...args: any[]) => console.info(...args),
    depuracion: (...args: any[]) => console.debug(...args),
    traza: (...args: any[]) => console.trace(...args),
    tiempo: (nombre: string) => console.time(nombre),
    tiempoFin: (nombre: string) => console.timeEnd(nombre),
    grupo: (...args: any[]) => console.group(...args),
    grupoFin: () => console.groupEnd(),
    tabla: (data: any) => console.table(data),
    limpiar: () => console.clear(),
    afirmar: (condition: boolean, ...args: any[]) => console.assert(condition, ...args),
    mostrar: (obj: any) => console.dir(obj),
    mostrarXML: (obj: any) => console.dirxml(obj),
    groupCollapsed: (...args: any[]) => console.groupCollapsed(...args),
    perfil: (label: string) => console.profile(label),
    terminarPerfil: () => console.profileEnd(),
    timeStamp: (label: string) => console.timeStamp(label),
    countador: (label?: string) => console.count(label),
    reinciarContador: (label?: string) => console.countReset(label),
};

