// consola.ts
export const 控制台 = {
    消息: (...args: any[]) => console.log(...args),
    错误: (...args: any[]) => console.error(...args),
    警告: (...args: any[]) => console.warn(...args),
    信息: (...args: any[]) => console.info(...args),
    调试: (...args: any[]) => console.debug(...args),
    跟踪: (...args: any[]) => console.trace(...args),
    时间: (名称: string) => console.time(名称),
    时间结束: (名称: string) => console.timeEnd(名称),
    组: (...args: any[]) => console.group(...args),
    组结束: () => console.groupEnd(),
    表格: (数据: any) => console.table(数据),
    清除: () => console.clear(),
    断言: (条件: boolean, ...args: any[]) => console.assert(条件, ...args),
    显示: (对象: any) => console.dir(对象),
    显示XML: (对象: any) => console.dirxml(对象),
    组折叠: (...args: any[]) => console.groupCollapsed(...args),
    个人资料: (标签: string) => console.profile(标签),
    结束个人资料: () => console.profileEnd(),
    时间戳: (标签: string) => console.timeStamp(标签),
    计数器: (标签?: string) => console.count(标签),
    重置计数器: (标签?: string) => console.countReset(标签),
};
