// console.ts
export const consoleFr = {
    message: (...args: any[]) => console.log(...args),
    erreur: (...args: any[]) => console.error(...args),
    avertissement: (...args: any[]) => console.warn(...args),
    info: (...args: any[]) => console.info(...args),
    depuration: (...args: any[]) => console.debug(...args),
    trace: (...args: any[]) => console.trace(...args),
    temps: (nom: string) => console.time(nom),
    tempsFin: (nom: string) => console.timeEnd(nom),
    groupe: (...args: any[]) => console.group(...args),
    groupeFin: () => console.groupEnd(),
    tableau: (data: any) => console.table(data),
    nettoyer: () => console.clear(),
    affirmer: (condition: boolean, ...args: any[]) => console.assert(condition, ...args),
    montrer: (obj: any) => console.dir(obj),
    montrerXML: (obj: any) => console.dirxml(obj),
    groupePlie: (...args: any[]) => console.groupCollapsed(...args),
    profil: (label: string) => console.profile(label),
    terminerProfil: () => console.profileEnd(),
    horodateur: (label: string) => console.timeStamp(label),
    compteur: (label?: string) => console.count(label),
    reinitialiserCompteur: (label?: string) => console.countReset(label),
};
