// konsole.ts
export const konsole = {
    nachricht: (...args: any[]) => console.log(...args),
    fehler: (...args: any[]) => console.error(...args),
    warnung: (...args: any[]) => console.warn(...args),
    info: (...args: any[]) => console.info(...args),
    debuggen: (...args: any[]) => console.debug(...args),
    rückverfolgung: (...args: any[]) => console.trace(...args),
    zeit: (name: string) => console.time(name),
    zeitEnde: (name: string) => console.timeEnd(name),
    gruppe: (...args: any[]) => console.group(...args),
    gruppeEnde: () => console.groupEnd(),
    tabelle: (daten: any) => console.table(daten),
    löschen: () => console.clear(),
    bestätigen: (bedingung: boolean, ...args: any[]) => console.assert(bedingung, ...args),
    anzeigen: (obj: any) => console.dir(obj),
    anzeigenXML: (obj: any) => console.dirxml(obj),
    gruppenZusammengeklappt: (...args: any[]) => console.groupCollapsed(...args),
    profil: (bezeichnung: string) => console.profile(bezeichnung),
    profilBeenden: () => console.profileEnd(),
    zeitStempel: (bezeichnung: string) => console.timeStamp(bezeichnung),
    zähler: (bezeichnung?: string) => console.count(bezeichnung),
    zurücksetzenZähler: (bezeichnung?: string) => console.countReset(bezeichnung),
};
